### ISSUE TITLE
Unexpected breakage of existing functionality

### ISSUE THREAD

**Issue by wkoffel** [gunpowderlabs/buildpack-ruby-db-migrate#1]
Seems like this buildpack was moved towards more generic rake execution, which is totally cool.  I've updated my app to use the new buildpack-ruby-rake-deploy-tasks.

**However**....I discovered this because I did a deploy of my production app, and the migrations didn't run, breaking the app!  Eek.  Might I suggest that the behavior in this buildpack be restored, and maybe print out a deprecation warning so others have a smoother transition?  I'm guessing there are a number of folks who are having a bad surprise right now.

Shame on me for not forking the buildpack (I've done that with others, but referenced this directly).  I'm guessing I'm not the only one....

**Comment by psyho** [comment]
I'm really sorry for breaking your deploy process. I updated our own applications before pushing this change and completely forgotten that there might be other people using this tool as well. Thank you for pointing out this issue.

Like you suggested I restored the original functionality by defaulting DEPLOY_TASKS to db:migrate and added a deprecation warning.

**Comment by wkoffel** [comment]
Thanks psyho.  No worries on the build, we learned quickly and fixed it.  Thanks for your work on these buildpacks in general, they are simple but helpful to not have to reinvent.  Hopefully this revert will make someone else's upgrade path smoother!
